name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - shell: bash
      env:
          SUPER_SECRET: ${{ secrets.secret }}
      run: brew install git-secret


    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: gpg key
      run: git secret cat
    - name: Build with Gradle
      run: ./gradlew build
